/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package automated.sas;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Smoker
 */
public class Lecturers_list extends javax.swing.JFrame {

    /**
     * Creates new form Lecturers_list
     */
    
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    String sql;
    
    public Lecturers_list() {
        initComponents();
        conn=DBConnect.connect();
     ;
        getTeacherData();
        getWholeTeacherData();
        
        // Set up the JTable mouse click listener
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        dashboard_back = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Teacher Id", "Teacher Name", "Faculty", "Teacher Unit", "Added On", "Fingerprint"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 290));

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N

        dashboard_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dashboard_2.png"))); // NOI18N
        dashboard_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboard_backActionPerformed(evt);
            }
        });
        jMenu4.add(dashboard_back);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void getTeacherData() {
        try {
            DefaultTableModel dt = (DefaultTableModel)jTable1.getModel();
            String sql= "select teacher_id as 'Teacher Id',  teacher_name as 'Teacher Name', teacher_faculty as 'Faculty' , teacher_unit as 'Teacher Unit', added_on as 'Added On', fingerprint as 'Fingerprint'  from tbl_teacher";
            pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
          
            jTable1.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            
                    
            
        }
        catch(Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    /**
     * Teacher Data
     */
    public void getWholeTeacherData() {
        try {
            DefaultTableModel dt = (DefaultTableModel)jTable1.getModel();
            
            String sql="select teacher_id as 'Teacher Id',  teacher_name as 'Teacher Name',  teacher_faculty as 'Faculty', teacher_unit as 'Teacher Unit',added_on as 'Added On', fingerprint as 'Fingerprint' from tbl_teacher";
            pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
          
            jTable1.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
              
        }
        catch(Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
   
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void dashboard_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboard_backActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
         setVisible(false);
        new Admin_Dashboard().setVisible(true); 
    }//GEN-LAST:event_dashboard_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lecturers_list().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem dashboard_back;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
